### ISSUE TITLE
No module named 'defopt'

### ISSUE THREAD

**Issue by krothschild** [nh13/gedmatch-tools#1]
I installed on Ubuntu, but when I go to try to run it, I get the following error:

kar@kar-MS-7B50:/usr/local/bin$ sudo gedmatch-tools --help
Traceback (most recent call last):
  File "/usr/local/bin/gedmatch-tools", line 33, in <module>
    sys.exit(load_entry_point('gedmatch-tools==0.0.1', 'console_scripts', 'gedmatch-tools')())
  File "/usr/local/bin/gedmatch-tools", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/lib/python3.9/dist-packages/gedmatch_tools-0.0.1-py3.9.egg/gedmatch_tools/__main__.py", line 3, in <module>
    import defopt
ModuleNotFoundError: No module named 'defopt'

**Comment by nh13** [comment]
Sorry, I am no longer maintaining this repo.  try installing defopt with conda or pip.  Sorry I cannot be more help.
